### ISSUE TITLE
Certificate warning when visiting grafeas.io

### ISSUE THREAD

**Issue by hlgr360** [Grafeas/grafeas.github.io#2]
It does not exactly install confidence into the project if visiting grafeas.io gives you the following warning (on Safari)

![screen shot 2017-10-21 at 12 01 25 pm](https://user-images.githubusercontent.com/5970396/31850733-f1ab1fce-b657-11e7-9e42-1b30aeb13d7b.png)

**Comment by suteebu** [comment]
Hi Holger, thanks for identifying this issue. I’m looking at how to setup HTTPS with a custom domain on GitHub Pages. Trying to resolve what I think is a CNAME flattening issue with CloudFlare.

**Comment by suteebu** [comment]
I believe I've fixed the issue and validated that https works on my and my co-workers browsers. (Please re-open if I'm mistaken!)

**Comment by hlgr360** [comment]
+1
