### ISSUE TITLE
Issue with _docs/concepts/what-is-kritis/overview.md - broken link

### ISSUE THREAD

**Issue by toli** [Grafeas/grafeas.github.io#20]
wrong link to tutorial in 
`Kritis Beta release is available here. For more information, see the tutorial.`

it goes to https://github.com/grafeas/kritis/blob/master/tutorial.md but should be https://github.com/grafeas/kritis/blob/master/docs/tutorial.md instead

**Comment by aysylu** [comment]
Thanks for reporting! The PR with the fix is in review.
