### ISSUE TITLE
base.html refers to Istio's description

### ISSUE THREAD

**Issue by meganokeefe** [Grafeas/grafeas.github.io#22]
The base HTML for the Github pages site refers to Istio, not Grafeas:

https://github.com/grafeas/grafeas.github.io/blob/master/_layouts/base.html#L17

And when I Google search Grafeas, I see:
<img width="665" alt="screen shot 2018-12-04 at 11 22 23 am" src="https://user-images.githubusercontent.com/3137106/49467252-e3a2b580-f7b6-11e8-95c2-38853956d9fd.png">

**Comment by aysylu** [comment]
Good catch, @m-okeefe! Thank you for reporting.
