### ISSUE TITLE
grafeas.io site is not working

### ISSUE THREAD

**Issue by ghost** [Grafeas/grafeas.github.io#25]
The site links are broken 
e.g. https://grafeas.io/docs/reference/notes/ gives 404.

**Comment by ghost** [comment]
@aysylu , It seems that recent merges have removed the top header. Are there any plan to update the documentation?

- Arvind

**Comment by aysylu** [comment]
@aku163 May I ask how you got to that specific page? Our goal is to combine the documentation on the GitHub page and here and have a more streamlined way to onboard. All the information that was on that page before should now be available in https://github.com/grafeas/grafeas/blob/master/docs/release_notes.md. Please LMK if anything is missing. Thanks!

**Comment by ghost** [comment]
Thanks @aysylu for the response. 

Around 2 weeks back, I could see headers like about about, docs, blog, community with [github page url](https://grafeas.io/) but it is missing. 

![image](https://user-images.githubusercontent.com/10303369/51698350-d4472800-2001-11e9-92f1-9485222e4e48.png)

I did notice this, as the urls were bookmarked. It's hard to navigate on site, even custom search are landing to google cached results {old urls now}.

-
Arvind

**Comment by aysylu** [comment]
Got it, thanks for clarifying @aku163. Going forward, this grafeas.io page is only meant as a landing page. All of the information has been moved to https://github.com/grafeas/grafeas to streamline onboarding of contributors.

**Comment by ghost** [comment]
Alright, Thanks.
